
import React from 'react';
import {
  View,
  Text,
  TouchableOpacity,
  StyleSheet,
  ScrollView,
  Platform,
  Linking,
} from 'react-native';
import { router } from 'expo-router';
import { colors, commonStyles } from '@/styles/commonStyles';
import { IconSymbol } from '@/components/IconSymbol';

export default function RequestAccessScreen() {
  const handleContactSupport = () => {
    // Open email client
    Linking.openURL('mailto:support@campsync.com?subject=Authorization Code Request');
  };

  return (
    <View style={commonStyles.container}>
      <ScrollView
        contentContainerStyle={styles.scrollContent}
        showsVerticalScrollIndicator={false}
      >
        {/* Header */}
        <View style={styles.header}>
          <TouchableOpacity style={styles.backButton} onPress={() => router.back()}>
            <IconSymbol
              ios_icon_name="chevron.left"
              android_material_icon_name="arrow-back"
              size={24}
              color={colors.primary}
            />
          </TouchableOpacity>
          <View style={styles.logoContainer}>
            <IconSymbol
              ios_icon_name="key.fill"
              android_material_icon_name="vpn-key"
              size={48}
              color={colors.primary}
            />
          </View>
          <Text style={styles.title}>Need an Authorization Code?</Text>
          <Text style={styles.subtitle}>
            CampSync uses secure authorization codes to control access
          </Text>
        </View>

        {/* Info Sections */}
        <View style={styles.section}>
          <View style={[commonStyles.card, styles.infoCard]}>
            <View style={styles.iconHeader}>
              <IconSymbol
                ios_icon_name="person.badge.key.fill"
                android_material_icon_name="admin-panel-settings"
                size={32}
                color={colors.primary}
              />
              <Text style={styles.cardTitle}>For Staff & Administrators</Text>
            </View>
            <Text style={commonStyles.textSecondary}>
              If you&apos;re a staff member or administrator, contact your camp&apos;s super administrator to receive an authorization code.
            </Text>
            <View style={styles.bulletList}>
              <View style={styles.bulletItem}>
                <Text style={styles.bullet}>•</Text>
                <Text style={commonStyles.textSecondary}>
                  Codes are generated by camp administrators
                </Text>
              </View>
              <View style={styles.bulletItem}>
                <Text style={styles.bullet}>•</Text>
                <Text style={commonStyles.textSecondary}>
                  Each code assigns your role (staff or admin)
                </Text>
              </View>
              <View style={styles.bulletItem}>
                <Text style={styles.bullet}>•</Text>
                <Text style={commonStyles.textSecondary}>
                  Codes may have expiration dates
                </Text>
              </View>
            </View>
          </View>

          <View style={[commonStyles.card, styles.infoCard]}>
            <View style={styles.iconHeader}>
              <IconSymbol
                ios_icon_name="envelope.badge.fill"
                android_material_icon_name="mark-email-unread"
                size={32}
                color={colors.accent}
              />
              <Text style={styles.cardTitle}>For Parents</Text>
            </View>
            <Text style={commonStyles.textSecondary}>
              Parents receive authorization codes automatically via email when their child is registered for camp.
            </Text>
            <View style={styles.bulletList}>
              <View style={styles.bulletItem}>
                <Text style={styles.bullet}>•</Text>
                <Text style={commonStyles.textSecondary}>
                  Check your email for an invitation
                </Text>
              </View>
              <View style={styles.bulletItem}>
                <Text style={styles.bullet}>•</Text>
                <Text style={commonStyles.textSecondary}>
                  Codes are linked to your child(ren)
                </Text>
              </View>
              <View style={styles.bulletItem}>
                <Text style={styles.bullet}>•</Text>
                <Text style={commonStyles.textSecondary}>
                  Usually single-use and expire in 30 days
                </Text>
              </View>
            </View>
          </View>

          <View style={[commonStyles.card, styles.warningCard]}>
            <View style={styles.iconHeader}>
              <IconSymbol
                ios_icon_name="exclamationmark.triangle.fill"
                android_material_icon_name="warning"
                size={32}
                color={colors.warning}
              />
              <Text style={styles.cardTitle}>Why Authorization Codes?</Text>
            </View>
            <Text style={commonStyles.textSecondary}>
              CampSync uses authorization codes to ensure:
            </Text>
            <View style={styles.bulletList}>
              <View style={styles.bulletItem}>
                <Text style={styles.bullet}>✓</Text>
                <Text style={commonStyles.textSecondary}>
                  No spam or unauthorized accounts
                </Text>
              </View>
              <View style={styles.bulletItem}>
                <Text style={styles.bullet}>✓</Text>
                <Text style={commonStyles.textSecondary}>
                  Proper role assignment and access control
                </Text>
              </View>
              <View style={styles.bulletItem}>
                <Text style={styles.bullet}>✓</Text>
                <Text style={commonStyles.textSecondary}>
                  Accurate parent-to-camper linking
                </Text>
              </View>
              <View style={styles.bulletItem}>
                <Text style={styles.bullet}>✓</Text>
                <Text style={commonStyles.textSecondary}>
                  Complete audit trail of all users
                </Text>
              </View>
            </View>
          </View>
        </View>

        {/* Contact Support */}
        <View style={styles.section}>
          <Text style={styles.sectionTitle}>Need Help?</Text>
          <TouchableOpacity
            style={[commonStyles.card, styles.contactCard]}
            onPress={handleContactSupport}
            activeOpacity={0.7}
          >
            <IconSymbol
              ios_icon_name="envelope.fill"
              android_material_icon_name="email"
              size={24}
              color={colors.primary}
            />
            <View style={styles.contactContent}>
              <Text style={styles.contactTitle}>Contact Support</Text>
              <Text style={commonStyles.textSecondary}>
                support@campsync.com
              </Text>
            </View>
            <IconSymbol
              ios_icon_name="chevron.right"
              android_material_icon_name="chevron-right"
              size={24}
              color={colors.textSecondary}
            />
          </TouchableOpacity>
        </View>

        {/* Back to Sign In */}
        <View style={styles.footer}>
          <TouchableOpacity
            style={styles.backToSignIn}
            onPress={() => router.replace('/sign-in')}
          >
            <Text style={styles.backToSignInText}>Back to Sign In</Text>
          </TouchableOpacity>
        </View>
      </ScrollView>
    </View>
  );
}

const styles = StyleSheet.create({
  scrollContent: {
    flexGrow: 1,
    paddingHorizontal: 24,
    paddingTop: Platform.OS === 'android' ? 60 : 40,
    paddingBottom: 40,
  },
  header: {
    alignItems: 'center',
    marginBottom: 32,
  },
  backButton: {
    position: 'absolute',
    left: 0,
    top: 0,
    padding: 8,
  },
  logoContainer: {
    width: 80,
    height: 80,
    borderRadius: 40,
    backgroundColor: colors.card,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 16,
    boxShadow: '0px 4px 12px rgba(0, 0, 0, 0.1)',
    elevation: 4,
  },
  title: {
    fontSize: 24,
    fontWeight: '800',
    color: colors.text,
    marginBottom: 4,
    textAlign: 'center',
  },
  subtitle: {
    fontSize: 14,
    color: colors.textSecondary,
    textAlign: 'center',
  },
  section: {
    marginBottom: 24,
  },
  sectionTitle: {
    fontSize: 20,
    fontWeight: '700',
    color: colors.text,
    marginBottom: 12,
  },
  infoCard: {
    marginBottom: 16,
  },
  warningCard: {
    backgroundColor: '#FFF8E1',
    marginBottom: 16,
  },
  iconHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 12,
    gap: 12,
  },
  cardTitle: {
    fontSize: 18,
    fontWeight: '700',
    color: colors.text,
    flex: 1,
  },
  bulletList: {
    marginTop: 12,
    gap: 8,
  },
  bulletItem: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 8,
  },
  bullet: {
    fontSize: 16,
    fontWeight: '700',
    color: colors.primary,
    width: 16,
  },
  contactCard: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  contactContent: {
    flex: 1,
  },
  contactTitle: {
    fontSize: 16,
    fontWeight: '600',
    color: colors.text,
    marginBottom: 2,
  },
  footer: {
    alignItems: 'center',
    marginTop: 'auto',
    paddingTop: 24,
  },
  backToSignIn: {
    paddingVertical: 12,
    paddingHorizontal: 24,
  },
  backToSignInText: {
    fontSize: 16,
    fontWeight: '600',
    color: colors.primary,
  },
});
